enum MessageType
{
    MSG_NEW = 0,
    MSG_OPEN,
    MSG_SAVE,
    MSG_UNDO,
    MSG_REDO,
    MSG_VERSION,
    MSG_RESUME,
    MSG_SHUTDOWN,
    MSG_DROP_CUBE,
    //
    RESPONSE_NEW,
    RESPONSE_OPEN,
    RESPONSE_SAVE,
    RESPONSE_UNDO,
    RESPONSE_REDO,
    RESPONSE_VERSION,
    RESPONSE_RESUME,
    RESPONSE_SHUTDOWN,
    RESPONSE_DROP_CUBE,
}